apiVersion: batch/v1
kind: Job
metadata:
  name: poet
spec:
  template:
    metadata:
      name: poet
    spec:
      volumes:
      - name: poet-pv-storage
        nfs:
          server: opalhpc-1
          path: /scratch/nfs-share
      containers:
      - name: poet-cont
        image: docker.io/ofthewave/poet-repo 
        command:
         - "/bin/bash"
        args: ["-c", "while true; do date >> /persistent/test.txt; sleep 5; done"]
        volumeMounts:
        - name: "poet-pv-storage"
          mountPath: "/persistent"
      restartPolicy: Never
